### ISSUE TITLE
PRTG data in bytes/sec, not in bits/sec

### ISSUE THREAD

**Issue by ffkammer** [neuralfraud/grafana-prtg#118]
Hi I've a serious problema trying to use the PRTG with grafana and grafana-prtg plugin, the traffic data is in bytes/sec and not in bits/sec and then the grafana plots the graph wrong.

Can you help me to solve this issue? I tried some colegues suggestions without success.

**Comment by Yakelixir** [comment]
This should be a setting that you can change under axis as displayed...

![screen shot 2018-11-19 at 11 58 17 am](https://user-images.githubusercontent.com/5784897/48722631-7c033c80-ebf2-11e8-923e-71e3365254bf.png)

**Comment by ffkammer** [comment]
Hi @Yakelixir it'snt, I configureted right using bits/sec (and tried bytes/sec), but the value displayed is 8 times less than the right value.

I've used the grafana with Zabbix with sucess but together with PRTG I've this issue.

Regards

**Comment by Yakelixir** [comment]
If this is a PRTG issue due to the fact that you stated that you were using bits and it was still 8x less. Which should only be the case if you have the axis set to bits/sec instead of bytes/sec. If this is still the case you could use a sensor factory to set a 8x multiplier on the sensor data before PRTG takes it in. I know this is non-optimal if this is the case...

**Comment by neuralfraud** [comment]
This is not a bug. This is how PRTG works. PRTG gives us Bytes. 

See latest master commit, there is a new multiplier option for bitheads who insist on seeing this data as bits/sec :)
