### ISSUE TITLE
Cannot read data

### ISSUE THREAD

**Issue by criskolkman** [neuralfraud/grafana-prtg#156]
Hello,

I'm just starting to use Grafana and I'm using the PRTG addon to create PRTG dashboards.
I keep getting the error `Cannot read property '1' of null` (see screenshot).
Any idea what is going wrong?

![image](https://user-images.githubusercontent.com/17678609/74752689-5b9bb500-526f-11ea-9c39-d06ca5e88cfe.png)

**Comment by angela-d** [comment]
Is the rest of your API connection working?
(Did you go through the 'test' during setup?)

I just tested a similar setup to your screenshot and got a result.

I'm new to this plugin too and the documentation in the wiki sucks, so I [wrote down everything](https://github.com/angela-d/brain-dump/tree/master/grafana-prtg) I did - see if any of my notes help.

I ran into this before, too.  It was because my target sensor didn't have any data for the default time range.

(For me):
Cause:

- (In PRTG) Device/Sensor Settings > Scanning Interval: 4 hours

Why it Caused the Map to Return as Undefined:

- The dashboard (Grafana) is set to pull data from the last 6 hours

[My fix](https://github.com/angela-d/brain-dump/blob/master/grafana-prtg/troubleshooting.md)

**Comment by criskolkman** [comment]
> Is the rest of your API connection working?
> (Did you go through the 'test' during setup?)
> 
> I just tested a similar setup to your screenshot and got a result.
> 
> I'm new to this plugin too and the documentation in the wiki sucks, so I [wrote down everything](https://github.com/angela-d/brain-dump/tree/master/grafana-prtg) I did - see if any of my notes help.
> 
> I ran into this before, too. It was because my target sensor didn't have any data for the default time range.
> 
> (For me):
> Cause:
> 
> * (In PRTG) Device/Sensor Settings > Scanning Interval: 4 hours
> 
> Why it Caused the Map to Return as Undefined:
> 
> * The dashboard (Grafana) is set to pull data from the last 6 hours
> 
> [My fix](https://github.com/angela-d/brain-dump/blob/master/grafana-prtg/troubleshooting.md)

Hello Angela,

I did use your github since the documentation on this github isn't the best.

Thank you for your answer, it seems that it had to do with the time settings for the API user (https://github.com/angela-d/brain-dump/blob/master/grafana-prtg/troubleshooting.md#query--metrics--can-only-select-), will test some more but I'm getting a bit more info now!

**Comment by angela-d** [comment]
I ran into another cause of 'l is undefined' today, updated my notes: https://github.com/angela-d/brain-dump/blob/master/grafana-prtg/troubleshooting.md

Cause 2:
- A device (or sensor) in the target group is paused

Fix:
- Unpause (or remove the device from the group)
- Refresh the dashboard
