### ISSUE TITLE
SNMP Bandwidth Sensors

### ISSUE THREAD

**Issue by solaris187** [neuralfraud/grafana-prtg#3]
SNMP Bandwidth sensors do not appear to work with the grafana plugin. Data is not displayed on the graphs.

**Comment by neuralfraud** [comment]
What time range did you select? have you tried using the dev console to see if there was any exception? also, if you look at the requests to "/api/histdata.json, you should be able to see if it sent a response. Sometimes it sends "Not enough data"

Curiously ..what channel did you select? some of those SNMP sensors have channels for status and then for the values. Any info you can provide from the console would be helpful!

**Comment by neuralfraud** [comment]
I think this might have to due with improper reading of the channel name -  I've noticed it does this on a few types of performance counters, such as IIS and SNMP interface metrics. This might be solved by changing line 374 of api_wrapper.js to regex match channel name to whats been returned by the PRTG server. It seems that when we query the PRTG API for a list of channels, it sends them like "Bytes Sent", etc. but the data has "Bytes Sent (volume)" and "Bytes Sent (speed)" - both with the same numeric ID. So that's confusing. Since both will match, and "(speed)" is the second result, that's most likely to be the metric you'll get.

I'll check this out when i get out of the office and see if I can implement a reliable solution.

**Comment by neuralfraud** [comment]
Please check out the commit referenced above - this should provide a usable workaround.

**Comment by jwlar** [comment]
Issue seems to have cropped up with the latest 3.0 version
