### ISSUE TITLE
Problem With API Connection in PRTG 16.1.21.1421/1422

### ISSUE THREAD

**Issue by ptcfast2** [neuralfraud/grafana-prtg#8]
I've been trying to get Grafana to connect to my newly updated PRTG installation but I've yet to have luck. For whatever reason I get the following error when testing connectivity within Grafana even with the URL field correctly filled out: 

Unknown error
Cannot read property 'url' of undefined

Grafana version is 2.5.0. I tried with 2.6.0 as well with no luck.

**Comment by neuralfraud** [comment]
Show some screenshots or copy&paste browser javascript console output,
please.

make sure api url includes /api

**Comment by ptcfast2** [comment]
Sure thing! Let me know if I can do anything more to help.
![image](https://cloud.githubusercontent.com/assets/16966701/12725651/96081a24-c8c8-11e5-8e74-7b6ffff75529.png)
![image](https://cloud.githubusercontent.com/assets/16966701/12725677/ac20eeee-c8c8-11e5-9d8e-c22f9f3cd2b7.png)

**Comment by neuralfraud** [comment]
bloody strange. I'll take a look today. and also, which version of Grafana?

**Comment by ptcfast2** [comment]
I'm presently running 2.5.0 but also tried with 2.6.0 before reverting. Same issue on both.

**Comment by neuralfraud** [comment]
Ok. The javascript code isn't that great! it's most likely failing due to the Access Control Origin header ...you did set that up right? HKLM\SOFTWARE\Wow6432Node\Paessler\PRTG Network Monitor\Server\Webserver? String value "AccessControlAllowOriginHTTPHeader" (REG_SZ) needs to match the URL you use to access grafana (because you're using the proxy feature). If it's not specified, OR it doesn't match, then the connection will fail (unless you use https - which for whatever reason just works)

**Comment by neuralfraud** [comment]
you can also set it to *

**Comment by ptcfast2** [comment]
Yeah I have that set in the registry. I've tried both ways - with the * and the actual URL. Tried, HTTP, HTTPS, different addresses and still no dice. Tried running Grafana on the server and off the server as well. Off the server with proxy and no proxy. Same result every time.

![image](https://cloud.githubusercontent.com/assets/16966701/12760622/179c7ce6-c99c-11e5-87a4-35591c1c07de.png)

**Comment by neuralfraud** [comment]
Only other thing i can think of is that you're accessing a site with an untrusted certificate (because you're accessing via IP). The weird unexpected token error though, that's an internal function... which is strange, by any chance does your password contain some very bizarre and/or strange characters?

**Comment by ptcfast2** [comment]
It was the password. We use very complex stuff, so I took it down a notch and it's working now. Thanks for the suggestion!

**Comment by neuralfraud** [comment]
if you dont mind, since its changed, what did you use outside of the normal A-Za-z0-9 character set?

**Comment by ptcfast2** [comment]
" % ' ?
